# -*- coding: utf-8 -*-
"""backgroumremover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UlrFU-gtix3bIqstgKgqwZJaNUwXrxa
"""

!mkdir data

from PIL import Image
import numpy as np
import io

def remove_white_background(input_path, output_path):
    img = Image.open(input_path).convert("RGBA")
    data = np.array(img)
    r, g, b, a = data.T
    white_areas = (r > 240) & (g > 240) & (b > 240)

    data[..., :-1][white_areas.T] = (255, 255, 255)
    data[..., -1][white_areas.T] = 0

    new_img = Image.fromarray(data)


    new_img.save(output_path, format="PNG")

from google.colab import files
uploaded = files.upload()
input_filename = next(iter(uploaded))
input_path = f"/content/{input_filename}"

output_path = "/content/output.png"

remove_white_background(input_path, output_path)

from IPython.display import Image, display
display(Image(filename=output_path))
files.download(output_path)



